\input texinfo   @c -*-texinfo-*-
@comment %**start of header (This is for running Texinfo on a region.)
@setfilename ../doc/src.info
@settitle Muq Source Code
@setchapternewpage odd
@comment %**end of header (This is for running Texinfo on a region.)
@c
@ifinfo
Copyright @copyright{} 1995 Jeff Prothero.
@end ifinfo
@c --------------------------------------------------------
@titlepage
@sp 10
@center @titlefont{Muq Source Code}
@sp 2
@c @center Version -1.0.0
@include versionc.t
@sp 2
@center Jeff Prothero
@center (cynbe@sl.tcp.com)
@c     ---------------------------------------------
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1995 Jeff Prothero.
@end titlepage
@c --------------------------------------------------------
@c Uncomment to generate a single index:
@c @synindex cp fn
@c @syncodeindex vr fn
@c @syncodeindex ky fn
@c @syncodeindex pg fn
@c @syncodeindex tp fn
@c
@node Top, Hacker Hints, , (dir)

@include versiont.t
This version of the manual is a second draft, and still very rough.

Internals and coding at the C level are not covered at all
yet, although the C code is copiously commented internally.

@menu
* Hacker Hints::
* Muq Internals::
* Muf Compiler::
* Function Index::
* Variable Index::
* Data Type Index::
* Concept Index::
@end menu

@include muqhint.t
@include muqimp.t
@include 120-C-muf.muf.tt

@node Function Index, Variable Index, Muf Compiler Wrapup, (dir)
@unnumbered Function Index

@printindex fn

@node Variable Index, Data Type Index, Function Index, (dir)
@unnumbered Variable Index

@printindex vr

@node Data Type Index, Concept Index, Variable Index, (dir)
@unnumbered Data Type Index

@printindex tp

@node Concept Index,  , Data Type Index, (dir)
@unnumbered Concept Index

@printindex cp

@c Tables of contents
@summarycontents
@contents

@bye
