extern int this_file;

/*--   Muq.h -- Master #include file for Muq.				*/
/* This file is formatted for emacs' outline-minor-mode.		*/
#ifndef INCLUDED_ALL_H
#define INCLUDED_ALL_H

/* These two go first so as */
/* to have first change at  */
/* defining stuff:          */
#include "Site-config.h"
#include "Defaults.h"

#include "Config.h"	/* Generated by GNU autoconfig script. 		*/
#include "Hax.h"	/* Portability stuff working with above.	*/
#include "Need.h"	/* Portability stuff working with above.	*/

#include "Version.h"	/* "-1.3.0" or such.				*/

#include "ary.h"
#include "asm.h"
#include "blk.h"
#include "bnm.h"
#include "bot.h"
#include "cdf.h"
#include "chr.h"
#include "cfg.h"
#include "cfn.h"
#include "clo.h"
#include "dbf.h"
#include "d3l.h"
#include "dil.h"
#include "ecn.h"
#include "err.h"
#include "eob.h"
#include "est.h"
#include "evc.h"
#include "evt.h"
#include "f32.h"
#include "f64.h"
#include "flt.h"
#include "fun.h"
#include "gfg.h"
#include "hsh.h"
#include "i01.h"
#include "i16.h"
#include "i32.h"
#include "int.h"
#include "key.h"
#include "skt.h"
#include "job.h"
#include "joq.h"
#include "jbs.h"
#include "lbd.h"
#include "lok.h"
#include "lst.h"
#include "mil.h"
#include "mod.h"
#include "mss.h"
#include "mtd.h"
#include "muf.h"
#include "muq.h"
#include "n3d.h"
#include "ndx.h"
#include "obj.h"
#include "ogl.h"
#include "pil.h"
#include "pkg.h"
#include "prx.h"
#include "stm.h"
#include "rdt.h"
#include "rex.h"
#include "sha.h"
#include "sel.h"
#include "set.h"
#include "sil.h"
#include "spc.h"
#include "ssn.h"
#include "stc.h"
#include "stk.h"
#include "sym.h"
#include "sys.h"
#include "stg.h"
#include "tbl.h"
#include "til.h"
#include "usr.h"
#include "usq.h"
#include "vec.h"
#include "wdw.h"
/* Commented out because nobody is working */
/* on completing the X support:            */
#ifdef MAYBE_SOMEDAY
#include "xcl.h"
#include "xcm.h"
#include "xcr.h"
#include "xdp.h"
#include "xft.h"
#include "xgc.h"
#include "xpx.h"
#include "xsc.h"
#include "xwd.h"
#endif

/* Include headers for emulation code: */
#define  MODULES_MUQ_H
#include "Modules.h"
#undef   MODULES_MUQ_H

#ifdef HAVE_MALLOC_H
#include <malloc.h>
#endif


/* Hark!  What rock through yonder window breaks? 			*/
/* What to do on fatal error:						*/
#ifndef MUQ_FATAL
#define MUQ_FATAL job_Fatal /* paren args separately */
#endif

/* What to do on usr error:						*/
#ifndef MUQ_WARN
#define MUQ_WARN job_Warn /* paren args separately */
#endif

/* Should have this default to (FALSE) in production mode: */
#ifndef MUQ_IS_PARANOID
#define MUQ_IS_PARANOID (TRUE)
#endif

/* Whether to include support for *_Invariants() and			*/
/* *_Print_State().  Since these are basically debug			*/
/* tools, bloatophobes may wish to suppress them. I'm			*/
/* inclined to include them in production use myself.			*/
/* Set to TRUE to compile, FALSE to not compile them:			*/
#ifndef MUQ_DEBUG
#define MUQ_DEBUG (1)
#endif


/* Set this TRUE to make Muq runs more repeatable.      */
/* Main effects of this are to suppress true randomness */
/* and to eliminate dates from the logs, so as to make  */
/* it easier to compare logs from one test run with     */
/* logs from another test run:                          */
#ifndef MUQ_REPEATABLE
#define MUQ_REPEATABLE (FALSE)
#endif

/* Set up parameters for vm.c: */
#define VM_WARN     MUQ_WARN
#define VM_FATAL    MUQ_FATAL
#define VM_DEBUG    MUQ_DEBUG
#define VM_NUKE_DB_AT_STARTUP (0)
#define VM_OCTAVE_FILE_PATH "muq"

/* lib.c declarations: */
extern Vm_Uch*  lib_Optional_Muf_Libraries;
extern Vm_Uch*  lib_Optional_Muf_Selfcheck_Libraries;
extern void     lib_Find_Srv_Directory( void );
extern void     lib_Validate_Srv_Directory( Vm_Uch* );
extern void     lib_Note_All_Muf_Libraries( void );
extern void*    lib_Malloc( Vm_Int );
extern Vm_Uch*  lib_Sprint( Vm_Uch*, Vm_Uch*, Vm_Uch*, ... );
extern Vm_Obj   lib_Validate_Symbol( Vm_Uch*, Vm_Obj );
extern FILE*    lib_Logfile;
extern char*    lib_Logfilename;
extern void     lib_Log_Printf( Vm_Uch*, ... );
extern void     lib_Log_String( Vm_Uch* );

/* This should likely be elsewhere: */
#if defined(HAVE_LIBGLUT) && defined(HAVE_GL_GL_H) && defined(HAVE_GL_GLU_H)
#define HAVE_OPENGL
#else
#undef  HAVE_OPENGL
#endif

/* Un/define this to dis/able malloc debugging via CrT_malloc wrappers: */
#undef CRT_MALLOC_SUPPORT

/* Un/define this to dis/able extra malloc heap validity checking via CrT_malloc wrappers: */
#undef CRT_DEBUG_ALSO (1)

#ifdef  CRT_MALLOC_SUPPORT
#include "CrT_malloc.h"
#endif


/************************************************************************/
/*-    File variables							*/
#endif /* INCLUDED_ALL_H */
/*

Local variables:
mode: outline-minor
outline-regexp: "[ \\t]*\/\\*-"
End:
*/



